---
ocp4_workload_metal_lb_namespace: metallb-system
ocp4_workload_metal_lb_channel: stable
ocp4_workload_metal_lb_automatic_install_plan_approval: false
ocp4_workload_metal_lb_starting_csv: metallb-operator.v4.20.0-202511040554
ocp4_workload_metal_lb_catalogsource_setup: false
ocp4_workload_metal_lb_catalogsource_name: metallb-system-catalogsource
ocp4_workload_metal_lb_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_metal_lb_catalog_snapshot_image_tag: v4.20_2025_11_04
ocp4_workload_metal_lb_ip_range_start: 200
ocp4_workload_metal_lb_ip_range_end: 210
# ocp4_workload_metal_lb_match_labels:
#   gateway.networking.k8s.io/gateway-name: data-science-gateway
